// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycles.sql

package dbgen

import (
	"context"
	"database/sql"

	dbutil "compound/internal/dbutil"
)

const autoCompleteCycle = `-- name: AutoCompleteCycle :execresult
UPDATE cycles SET status = 'completed', completed_at = ?, updated_at = ?
WHERE id = ?
`

type AutoCompleteCycleParams struct {
	CompletedAt dbutil.NullableTime
	UpdatedAt   dbutil.Time
	ID          int64
}

func (q *Queries) AutoCompleteCycle(ctx context.Context, arg AutoCompleteCycleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, autoCompleteCycle, arg.CompletedAt, arg.UpdatedAt, arg.ID)
}

const getCycleByUUID = `-- name: GetCycleByUUID :one
SELECT id, uuid, program_id, status, started_at, completed_at, created_at, updated_at
FROM cycles
WHERE uuid = ?
`

func (q *Queries) GetCycleByUUID(ctx context.Context, uuid string) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleByUUID, uuid)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProgramID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCycleInternalID = `-- name: GetCycleInternalID :one
SELECT id FROM cycles WHERE uuid = ?
`

func (q *Queries) GetCycleInternalID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCycleInternalID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSessionsByCycleID = `-- name: GetSessionsByCycleID :many
SELECT id, uuid, cycle_id, program_workout_id, sort_order, status, started_at, completed_at, notes, created_at, updated_at
FROM sessions
WHERE cycle_id = ?
ORDER BY sort_order
`

func (q *Queries) GetSessionsByCycleID(ctx context.Context, cycleID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByCycleID, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CycleID,
			&i.ProgramWorkoutID,
			&i.SortOrder,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCycle = `-- name: InsertCycle :execresult
INSERT INTO cycles (uuid, program_id, status, started_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCycleParams struct {
	Uuid      string
	ProgramID int64
	Status    string
	StartedAt dbutil.NullableTime
	CreatedAt dbutil.Time
	UpdatedAt dbutil.Time
}

func (q *Queries) InsertCycle(ctx context.Context, arg InsertCycleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCycle,
		arg.Uuid,
		arg.ProgramID,
		arg.Status,
		arg.StartedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const updateCycle = `-- name: UpdateCycle :execresult
UPDATE cycles
SET status = ?, completed_at = ?, updated_at = ?
WHERE uuid = ?
`

type UpdateCycleParams struct {
	Status      string
	CompletedAt dbutil.NullableTime
	UpdatedAt   dbutil.Time
	Uuid        string
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCycle,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.Uuid,
	)
}
