// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package dbgen

import (
	"context"
	"database/sql"

	dbutil "compound/internal/dbutil"
)

const getExerciseByUUID = `-- name: GetExerciseByUUID :one
SELECT id, uuid, name, muscle_group, equipment, tracking_type, notes, is_custom, created_at, updated_at
FROM exercises
WHERE uuid = ? AND deleted_at IS NULL
`

type GetExerciseByUUIDRow struct {
	ID           int64
	Uuid         string
	Name         string
	MuscleGroup  *string
	Equipment    *string
	TrackingType string
	Notes        *string
	IsCustom     bool
	CreatedAt    dbutil.Time
	UpdatedAt    dbutil.Time
}

func (q *Queries) GetExerciseByUUID(ctx context.Context, uuid string) (GetExerciseByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByUUID, uuid)
	var i GetExerciseByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.MuscleGroup,
		&i.Equipment,
		&i.TrackingType,
		&i.Notes,
		&i.IsCustom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertExercise = `-- name: InsertExercise :execresult
INSERT INTO exercises (uuid, name, muscle_group, equipment, tracking_type, notes, is_custom, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertExerciseParams struct {
	Uuid         string
	Name         string
	MuscleGroup  *string
	Equipment    *string
	TrackingType string
	Notes        *string
	IsCustom     bool
	CreatedAt    dbutil.Time
	UpdatedAt    dbutil.Time
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertExercise,
		arg.Uuid,
		arg.Name,
		arg.MuscleGroup,
		arg.Equipment,
		arg.TrackingType,
		arg.Notes,
		arg.IsCustom,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const softDeleteExercise = `-- name: SoftDeleteExercise :execresult
UPDATE exercises
SET deleted_at = ?, updated_at = ?
WHERE uuid = ? AND deleted_at IS NULL
`

type SoftDeleteExerciseParams struct {
	DeletedAt dbutil.NullableTime
	UpdatedAt dbutil.Time
	Uuid      string
}

func (q *Queries) SoftDeleteExercise(ctx context.Context, arg SoftDeleteExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteExercise, arg.DeletedAt, arg.UpdatedAt, arg.Uuid)
}

const updateExercise = `-- name: UpdateExercise :execresult
UPDATE exercises
SET name = ?, muscle_group = ?, equipment = ?, tracking_type = ?, notes = ?, updated_at = ?
WHERE uuid = ? AND deleted_at IS NULL
`

type UpdateExerciseParams struct {
	Name         string
	MuscleGroup  *string
	Equipment    *string
	TrackingType string
	Notes        *string
	UpdatedAt    dbutil.Time
	Uuid         string
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateExercise,
		arg.Name,
		arg.MuscleGroup,
		arg.Equipment,
		arg.TrackingType,
		arg.Notes,
		arg.UpdatedAt,
		arg.Uuid,
	)
}
