// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package dbgen

import (
	"context"
	"database/sql"

	dbutil "compound/internal/dbutil"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT method, path, status, response
FROM idempotency_keys
WHERE key = ? AND expires_at > ?
`

type GetIdempotencyKeyParams struct {
	Key       string
	ExpiresAt dbutil.Time
}

type GetIdempotencyKeyRow struct {
	Method   string
	Path     string
	Status   int64
	Response string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.Key, arg.ExpiresAt)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Method,
		&i.Path,
		&i.Status,
		&i.Response,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :execresult
INSERT INTO idempotency_keys (key, method, path, status, response, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIdempotencyKeyParams struct {
	Key       string
	Method    string
	Path      string
	Status    int64
	Response  string
	CreatedAt dbutil.Time
	ExpiresAt dbutil.Time
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertIdempotencyKey,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.Status,
		arg.Response,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
}
