// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	dbutil "compound/internal/dbutil"
)

type Cycle struct {
	ID          int64
	Uuid        string
	ProgramID   int64
	Status      string
	StartedAt   dbutil.NullableTime
	CompletedAt dbutil.NullableTime
	CreatedAt   dbutil.Time
	UpdatedAt   dbutil.Time
}

type Exercise struct {
	ID           int64
	Uuid         string
	Name         string
	MuscleGroup  *string
	Equipment    *string
	TrackingType string
	Notes        *string
	IsCustom     bool
	CreatedAt    dbutil.Time
	UpdatedAt    dbutil.Time
	DeletedAt    dbutil.NullableTime
}

type IdempotencyKey struct {
	ID        int64
	Key       string
	Method    string
	Path      string
	Status    int64
	Response  string
	CreatedAt dbutil.Time
	ExpiresAt dbutil.Time
}

type Program struct {
	ID          int64
	Uuid        string
	Name        string
	Description *string
	IsPrebuilt  bool
	CreatedAt   dbutil.Time
	UpdatedAt   dbutil.Time
	DeletedAt   dbutil.NullableTime
}

type ProgramWorkout struct {
	ID        int64
	Uuid      string
	ProgramID int64
	Name      string
	DayNumber int64
	SortOrder int64
	CreatedAt dbutil.Time
	UpdatedAt dbutil.Time
}

type ProgressionRule struct {
	ID                int64
	Uuid              string
	SectionExerciseID int64
	Strategy          string
	Increment         *float64
	IncrementPct      *float64
	DeloadThreshold   int64
	DeloadPct         float64
	CreatedAt         dbutil.Time
	UpdatedAt         dbutil.Time
}

type Section struct {
	ID               int64
	Uuid             string
	ProgramWorkoutID int64
	Name             string
	SortOrder        int64
	RestSeconds      *int64
	CreatedAt        dbutil.Time
	UpdatedAt        dbutil.Time
}

type SectionExercise struct {
	ID             int64
	Uuid           string
	SectionID      int64
	ExerciseID     int64
	TargetSets     *int64
	TargetReps     *int64
	TargetWeight   *float64
	TargetDuration *int64
	TargetDistance *float64
	SortOrder      int64
	Notes          *string
	CreatedAt      dbutil.Time
	UpdatedAt      dbutil.Time
}

type Session struct {
	ID               int64
	Uuid             string
	CycleID          int64
	ProgramWorkoutID int64
	SortOrder        int64
	Status           string
	StartedAt        dbutil.NullableTime
	CompletedAt      dbutil.NullableTime
	Notes            *string
	CreatedAt        dbutil.Time
	UpdatedAt        dbutil.Time
}

type SetLog struct {
	ID                int64
	Uuid              string
	SessionID         int64
	ExerciseID        int64
	SectionExerciseID *int64
	SetNumber         int64
	TargetReps        *int64
	ActualReps        *int64
	Weight            *float64
	Duration          *int64
	Distance          *float64
	Rpe               *float64
	CompletedAt       dbutil.Time
	CreatedAt         dbutil.Time
}
