// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package dbgen

import (
	"context"
	"database/sql"

	dbutil "compound/internal/dbutil"
)

const getProgramByUUID = `-- name: GetProgramByUUID :one
SELECT id, uuid, name, description, is_prebuilt, created_at, updated_at, deleted_at
FROM programs
WHERE uuid = ? AND deleted_at IS NULL
`

func (q *Queries) GetProgramByUUID(ctx context.Context, uuid string) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramByUUID, uuid)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.IsPrebuilt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProgramInternalID = `-- name: GetProgramInternalID :one
SELECT id FROM programs
WHERE uuid = ? AND deleted_at IS NULL
`

func (q *Queries) GetProgramInternalID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProgramInternalID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getWorkoutsForProgram = `-- name: GetWorkoutsForProgram :many
SELECT id, uuid, program_id, name, day_number, sort_order, created_at, updated_at
FROM program_workouts
WHERE program_id = ?
ORDER BY sort_order
`

func (q *Queries) GetWorkoutsForProgram(ctx context.Context, programID int64) ([]ProgramWorkout, error) {
	rows, err := q.db.QueryContext(ctx, getWorkoutsForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramWorkout
	for rows.Next() {
		var i ProgramWorkout
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ProgramID,
			&i.Name,
			&i.DayNumber,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasActiveCycle = `-- name: HasActiveCycle :one
SELECT COUNT(*) FROM cycles
WHERE program_id = ? AND status = 'active'
`

func (q *Queries) HasActiveCycle(ctx context.Context, programID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveCycle, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertProgram = `-- name: InsertProgram :execresult
INSERT INTO programs (uuid, name, description, is_prebuilt, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertProgramParams struct {
	Uuid        string
	Name        string
	Description *string
	IsPrebuilt  bool
	CreatedAt   dbutil.Time
	UpdatedAt   dbutil.Time
}

func (q *Queries) InsertProgram(ctx context.Context, arg InsertProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProgram,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.IsPrebuilt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const softDeleteProgram = `-- name: SoftDeleteProgram :execresult
UPDATE programs
SET deleted_at = ?, updated_at = ?
WHERE uuid = ? AND deleted_at IS NULL
`

type SoftDeleteProgramParams struct {
	DeletedAt dbutil.NullableTime
	UpdatedAt dbutil.Time
	Uuid      string
}

func (q *Queries) SoftDeleteProgram(ctx context.Context, arg SoftDeleteProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteProgram, arg.DeletedAt, arg.UpdatedAt, arg.Uuid)
}

const updateProgram = `-- name: UpdateProgram :execresult
UPDATE programs
SET name = ?, description = ?, updated_at = ?
WHERE uuid = ? AND deleted_at IS NULL
`

type UpdateProgramParams struct {
	Name        string
	Description *string
	UpdatedAt   dbutil.Time
	Uuid        string
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProgram,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.Uuid,
	)
}
