// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package dbgen

import (
	"context"

	dbutil "compound/internal/dbutil"
)

const countCompletedSessions = `-- name: CountCompletedSessions :one
SELECT COUNT(*) FROM sessions WHERE status = 'completed'
`

func (q *Queries) CountCompletedSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExerciseHistoryPage = `-- name: GetExerciseHistoryPage :many
SELECT s.id, s.uuid, s.completed_at, MAX(sl.weight) AS weight
FROM set_logs sl
JOIN sessions s ON s.id = sl.session_id
JOIN exercises e ON e.id = sl.exercise_id
WHERE e.uuid = ?
  AND s.status = 'completed'
  AND sl.weight IS NOT NULL
  AND (sl.target_reps IS NULL OR sl.actual_reps >= sl.target_reps)
GROUP BY sl.session_id, s.id, s.uuid, s.completed_at
ORDER BY s.completed_at DESC, s.id DESC
LIMIT ?
`

type GetExerciseHistoryPageParams struct {
	Uuid  string
	Limit int64
}

type GetExerciseHistoryPageRow struct {
	ID          int64
	Uuid        string
	CompletedAt dbutil.NullableTime
	Weight      interface{}
}

func (q *Queries) GetExerciseHistoryPage(ctx context.Context, arg GetExerciseHistoryPageParams) ([]GetExerciseHistoryPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseHistoryPage, arg.Uuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseHistoryPageRow
	for rows.Next() {
		var i GetExerciseHistoryPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CompletedAt,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseHistoryPageAfter = `-- name: GetExerciseHistoryPageAfter :many
SELECT s.id, s.uuid, s.completed_at, MAX(sl.weight) AS weight
FROM set_logs sl
JOIN sessions s ON s.id = sl.session_id
JOIN exercises e ON e.id = sl.exercise_id
WHERE e.uuid = ?
  AND s.status = 'completed'
  AND sl.weight IS NOT NULL
  AND (sl.target_reps IS NULL OR sl.actual_reps >= sl.target_reps)
  AND s.id < ?
GROUP BY sl.session_id, s.id, s.uuid, s.completed_at
ORDER BY s.completed_at DESC, s.id DESC
LIMIT ?
`

type GetExerciseHistoryPageAfterParams struct {
	Uuid  string
	ID    int64
	Limit int64
}

type GetExerciseHistoryPageAfterRow struct {
	ID          int64
	Uuid        string
	CompletedAt dbutil.NullableTime
	Weight      interface{}
}

func (q *Queries) GetExerciseHistoryPageAfter(ctx context.Context, arg GetExerciseHistoryPageAfterParams) ([]GetExerciseHistoryPageAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseHistoryPageAfter, arg.Uuid, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseHistoryPageAfterRow
	for rows.Next() {
		var i GetExerciseHistoryPageAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CompletedAt,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonalRecord = `-- name: GetPersonalRecord :one
SELECT sl.weight, sl.actual_reps, s.uuid, s.completed_at
FROM set_logs sl
JOIN sessions s ON s.id = sl.session_id
JOIN exercises e ON e.id = sl.exercise_id
WHERE e.uuid = ?
  AND s.status = 'completed'
  AND sl.weight IS NOT NULL
  AND (sl.target_reps IS NULL OR sl.actual_reps >= sl.target_reps)
ORDER BY sl.weight DESC, s.completed_at DESC
LIMIT 1
`

type GetPersonalRecordRow struct {
	Weight      *float64
	ActualReps  *int64
	Uuid        string
	CompletedAt dbutil.NullableTime
}

func (q *Queries) GetPersonalRecord(ctx context.Context, uuid string) (GetPersonalRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonalRecord, uuid)
	var i GetPersonalRecordRow
	err := row.Scan(
		&i.Weight,
		&i.ActualReps,
		&i.Uuid,
		&i.CompletedAt,
	)
	return i, err
}

const listSessionStatusNewestFirst = `-- name: ListSessionStatusNewestFirst :many
SELECT status FROM sessions
WHERE status IN ('completed', 'skipped')
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListSessionStatusNewestFirst(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionStatusNewestFirst)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
