// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countIncompleteSessionsInCycle = `-- name: CountIncompleteSessionsInCycle :one
SELECT COUNT(*) FROM sessions
WHERE cycle_id = ? AND status NOT IN ('completed', 'skipped')
`

func (q *Queries) CountIncompleteSessionsInCycle(ctx context.Context, cycleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIncompleteSessionsInCycle, cycleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSessionByUUID = `-- name: GetSessionByUUID :one
SELECT id, uuid, cycle_id, program_workout_id, sort_order, status, started_at, completed_at, notes, created_at, updated_at
FROM sessions
WHERE uuid = ?
`

func (q *Queries) GetSessionByUUID(ctx context.Context, uuid string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUUID, uuid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CycleID,
		&i.ProgramWorkoutID,
		&i.SortOrder,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionInternalID = `-- name: GetSessionInternalID :one
SELECT id FROM sessions WHERE uuid = ?
`

func (q *Queries) GetSessionInternalID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionInternalID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSetLogsBySessionID = `-- name: GetSetLogsBySessionID :many
SELECT id, uuid, session_id, exercise_id, section_exercise_id, set_number, target_reps, actual_reps, weight, duration, distance, rpe, completed_at, created_at
FROM set_logs
WHERE session_id = ?
ORDER BY set_number
`

func (q *Queries) GetSetLogsBySessionID(ctx context.Context, sessionID int64) ([]SetLog, error) {
	rows, err := q.db.QueryContext(ctx, getSetLogsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetLog
	for rows.Next() {
		var i SetLog
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SessionID,
			&i.ExerciseID,
			&i.SectionExerciseID,
			&i.SetNumber,
			&i.TargetReps,
			&i.ActualReps,
			&i.Weight,
			&i.Duration,
			&i.Distance,
			&i.Rpe,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :execresult
INSERT INTO sessions (uuid, cycle_id, program_workout_id, sort_order, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	Uuid             string
	CycleID          int64
	ProgramWorkoutID int64
	SortOrder        int64
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSession,
		arg.Uuid,
		arg.CycleID,
		arg.ProgramWorkoutID,
		arg.SortOrder,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertSetLog = `-- name: InsertSetLog :execresult
INSERT INTO set_logs (uuid, session_id, exercise_id, section_exercise_id, set_number, target_reps, actual_reps, weight, duration, distance, rpe, completed_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSetLogParams struct {
	Uuid              string
	SessionID         int64
	ExerciseID        int64
	SectionExerciseID *int64
	SetNumber         int64
	TargetReps        *int64
	ActualReps        *int64
	Weight            *float64
	Duration          *int64
	Distance          *float64
	Rpe               *float64
	CompletedAt       time.Time
	CreatedAt         time.Time
}

func (q *Queries) InsertSetLog(ctx context.Context, arg InsertSetLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSetLog,
		arg.Uuid,
		arg.SessionID,
		arg.ExerciseID,
		arg.SectionExerciseID,
		arg.SetNumber,
		arg.TargetReps,
		arg.ActualReps,
		arg.Weight,
		arg.Duration,
		arg.Distance,
		arg.Rpe,
		arg.CompletedAt,
		arg.CreatedAt,
	)
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions
SET status = ?, started_at = ?, completed_at = ?, notes = ?, updated_at = ?
WHERE uuid = ?
`

type UpdateSessionParams struct {
	Status      string
	StartedAt   *time.Time
	CompletedAt *time.Time
	Notes       *string
	UpdatedAt   time.Time
	Uuid        string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSession,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Notes,
		arg.UpdatedAt,
		arg.Uuid,
	)
}
