// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countIncompleteSessionsInCycle = `-- name: CountIncompleteSessionsInCycle :one
SELECT COUNT(*) FROM sessions
WHERE cycle_id = ? AND status NOT IN ('completed', 'skipped')
`

func (q *Queries) CountIncompleteSessionsInCycle(ctx context.Context, cycleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIncompleteSessionsInCycle, cycleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSetLogsForSessionAndExercise = `-- name: DeleteSetLogsForSessionAndExercise :exec
DELETE FROM set_logs
WHERE session_id = ? AND exercise_id = ?
`

type DeleteSetLogsForSessionAndExerciseParams struct {
	SessionID  int64
	ExerciseID int64
}

func (q *Queries) DeleteSetLogsForSessionAndExercise(ctx context.Context, arg DeleteSetLogsForSessionAndExerciseParams) error {
	_, err := q.db.ExecContext(ctx, deleteSetLogsForSessionAndExercise, arg.SessionID, arg.ExerciseID)
	return err
}

const getExerciseTrackingTypeByID = `-- name: GetExerciseTrackingTypeByID :one
SELECT tracking_type FROM exercises WHERE id = ?
`

func (q *Queries) GetExerciseTrackingTypeByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getExerciseTrackingTypeByID, id)
	var tracking_type string
	err := row.Scan(&tracking_type)
	return tracking_type, err
}

const getExerciseTrackingTypeBySectionExerciseID = `-- name: GetExerciseTrackingTypeBySectionExerciseID :one
SELECT e.tracking_type, e.id AS exercise_id
FROM section_exercises se
JOIN exercises e ON e.id = se.exercise_id
WHERE se.id = ?
`

type GetExerciseTrackingTypeBySectionExerciseIDRow struct {
	TrackingType string
	ExerciseID   int64
}

func (q *Queries) GetExerciseTrackingTypeBySectionExerciseID(ctx context.Context, id int64) (GetExerciseTrackingTypeBySectionExerciseIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExerciseTrackingTypeBySectionExerciseID, id)
	var i GetExerciseTrackingTypeBySectionExerciseIDRow
	err := row.Scan(&i.TrackingType, &i.ExerciseID)
	return i, err
}

const getSessionByUUID = `-- name: GetSessionByUUID :one
SELECT id, uuid, cycle_id, program_workout_id, sort_order, status, started_at, completed_at, notes, created_at, updated_at
FROM sessions
WHERE uuid = ?
`

func (q *Queries) GetSessionByUUID(ctx context.Context, uuid string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUUID, uuid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CycleID,
		&i.ProgramWorkoutID,
		&i.SortOrder,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionInternalID = `-- name: GetSessionInternalID :one
SELECT id FROM sessions WHERE uuid = ?
`

func (q *Queries) GetSessionInternalID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionInternalID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSetLogProgressionHistory = `-- name: GetSetLogProgressionHistory :many
SELECT sl.section_exercise_id, sl.set_number,
       sl.actual_reps, sl.target_reps, sl.weight,
       s.id AS session_id, s.completed_at
FROM set_logs sl
JOIN sessions s ON s.id = sl.session_id
WHERE sl.section_exercise_id IN (/*SLICE:section_exercise_ids*/?)
  AND s.status = 'completed'
ORDER BY sl.section_exercise_id, s.completed_at DESC, s.id DESC, sl.set_number ASC
`

type GetSetLogProgressionHistoryRow struct {
	SectionExerciseID *int64
	SetNumber         int64
	ActualReps        *int64
	TargetReps        *int64
	Weight            *float64
	SessionID         int64
	CompletedAt       *time.Time
}

func (q *Queries) GetSetLogProgressionHistory(ctx context.Context, sectionExerciseIds []*int64) ([]GetSetLogProgressionHistoryRow, error) {
	query := getSetLogProgressionHistory
	var queryParams []interface{}
	if len(sectionExerciseIds) > 0 {
		for _, v := range sectionExerciseIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:section_exercise_ids*/?", strings.Repeat(",?", len(sectionExerciseIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:section_exercise_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSetLogProgressionHistoryRow
	for rows.Next() {
		var i GetSetLogProgressionHistoryRow
		if err := rows.Scan(
			&i.SectionExerciseID,
			&i.SetNumber,
			&i.ActualReps,
			&i.TargetReps,
			&i.Weight,
			&i.SessionID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetLogsBySessionID = `-- name: GetSetLogsBySessionID :many
SELECT sl.id, sl.uuid, sl.session_id, sl.exercise_id, sl.section_exercise_id,
       sl.set_number, sl.target_reps, sl.actual_reps, sl.weight, sl.duration,
       sl.distance, sl.rpe, sl.completed_at, sl.created_at,
       e.uuid AS exercise_uuid,
       se.uuid AS section_exercise_uuid
FROM set_logs sl
JOIN exercises e ON e.id = sl.exercise_id
LEFT JOIN section_exercises se ON se.id = sl.section_exercise_id
WHERE sl.session_id = ?
ORDER BY sl.set_number
`

type GetSetLogsBySessionIDRow struct {
	ID                  int64
	Uuid                string
	SessionID           int64
	ExerciseID          int64
	SectionExerciseID   *int64
	SetNumber           int64
	TargetReps          *int64
	ActualReps          *int64
	Weight              *float64
	Duration            *int64
	Distance            *float64
	Rpe                 *float64
	CompletedAt         time.Time
	CreatedAt           time.Time
	ExerciseUuid        string
	SectionExerciseUuid *string
}

func (q *Queries) GetSetLogsBySessionID(ctx context.Context, sessionID int64) ([]GetSetLogsBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSetLogsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSetLogsBySessionIDRow
	for rows.Next() {
		var i GetSetLogsBySessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SessionID,
			&i.ExerciseID,
			&i.SectionExerciseID,
			&i.SetNumber,
			&i.TargetReps,
			&i.ActualReps,
			&i.Weight,
			&i.Duration,
			&i.Distance,
			&i.Rpe,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.ExerciseUuid,
			&i.SectionExerciseUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :execresult
INSERT INTO sessions (uuid, cycle_id, program_workout_id, sort_order, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	Uuid             string
	CycleID          int64
	ProgramWorkoutID int64
	SortOrder        int64
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSession,
		arg.Uuid,
		arg.CycleID,
		arg.ProgramWorkoutID,
		arg.SortOrder,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertSetLog = `-- name: InsertSetLog :execresult
INSERT INTO set_logs (uuid, session_id, exercise_id, section_exercise_id, set_number, target_reps, actual_reps, weight, duration, distance, rpe, completed_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSetLogParams struct {
	Uuid              string
	SessionID         int64
	ExerciseID        int64
	SectionExerciseID *int64
	SetNumber         int64
	TargetReps        *int64
	ActualReps        *int64
	Weight            *float64
	Duration          *int64
	Distance          *float64
	Rpe               *float64
	CompletedAt       time.Time
	CreatedAt         time.Time
}

func (q *Queries) InsertSetLog(ctx context.Context, arg InsertSetLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSetLog,
		arg.Uuid,
		arg.SessionID,
		arg.ExerciseID,
		arg.SectionExerciseID,
		arg.SetNumber,
		arg.TargetReps,
		arg.ActualReps,
		arg.Weight,
		arg.Duration,
		arg.Distance,
		arg.Rpe,
		arg.CompletedAt,
		arg.CreatedAt,
	)
}

const resolveSectionExercise = `-- name: ResolveSectionExercise :one
SELECT se.id AS section_exercise_id, e.id AS exercise_id, e.uuid AS exercise_uuid
FROM section_exercises se
JOIN exercises e ON e.id = se.exercise_id
WHERE se.uuid = ?
`

type ResolveSectionExerciseRow struct {
	SectionExerciseID int64
	ExerciseID        int64
	ExerciseUuid      string
}

func (q *Queries) ResolveSectionExercise(ctx context.Context, uuid string) (ResolveSectionExerciseRow, error) {
	row := q.db.QueryRowContext(ctx, resolveSectionExercise, uuid)
	var i ResolveSectionExerciseRow
	err := row.Scan(&i.SectionExerciseID, &i.ExerciseID, &i.ExerciseUuid)
	return i, err
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions
SET status = ?, started_at = ?, completed_at = ?, notes = ?, updated_at = ?
WHERE uuid = ?
`

type UpdateSessionParams struct {
	Status      string
	StartedAt   *time.Time
	CompletedAt *time.Time
	Notes       *string
	UpdatedAt   time.Time
	Uuid        string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSession,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Notes,
		arg.UpdatedAt,
		arg.Uuid,
	)
}
