// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"

	dbutil "compound/internal/dbutil"
)

const deleteSection = `-- name: DeleteSection :execresult
DELETE FROM sections
WHERE uuid = ?
`

func (q *Queries) DeleteSection(ctx context.Context, uuid string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSection, uuid)
}

const deleteSectionExercise = `-- name: DeleteSectionExercise :execresult
DELETE FROM section_exercises
WHERE uuid = ?
`

func (q *Queries) DeleteSectionExercise(ctx context.Context, uuid string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSectionExercise, uuid)
}

const deleteWorkout = `-- name: DeleteWorkout :execresult
DELETE FROM program_workouts
WHERE uuid = ?
`

func (q *Queries) DeleteWorkout(ctx context.Context, uuid string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWorkout, uuid)
}

const getDayNumbersForProgram = `-- name: GetDayNumbersForProgram :many
SELECT day_number FROM program_workouts
WHERE program_id = ?
ORDER BY day_number
`

func (q *Queries) GetDayNumbersForProgram(ctx context.Context, programID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getDayNumbersForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var day_number int64
		if err := rows.Scan(&day_number); err != nil {
			return nil, err
		}
		items = append(items, day_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxSectionExerciseSortOrder = `-- name: GetMaxSectionExerciseSortOrder :one

SELECT COALESCE(MAX(sort_order), 0) FROM section_exercises
WHERE section_id = ?
`

// ============================================================
// section_exercises
// ============================================================
func (q *Queries) GetMaxSectionExerciseSortOrder(ctx context.Context, sectionID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxSectionExerciseSortOrder, sectionID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getMaxSectionSortOrder = `-- name: GetMaxSectionSortOrder :one
SELECT COALESCE(MAX(sort_order), 0) FROM sections
WHERE program_workout_id = ?
`

func (q *Queries) GetMaxSectionSortOrder(ctx context.Context, programWorkoutID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxSectionSortOrder, programWorkoutID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getMaxWorkoutSortOrder = `-- name: GetMaxWorkoutSortOrder :one

SELECT COALESCE(MAX(sort_order), 0) FROM program_workouts
WHERE program_id = ?
`

// ============================================================
// program_workouts
// ============================================================
func (q *Queries) GetMaxWorkoutSortOrder(ctx context.Context, programID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxWorkoutSortOrder, programID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getProgressionRuleBySectionExerciseID = `-- name: GetProgressionRuleBySectionExerciseID :one
SELECT id, uuid, section_exercise_id, strategy, increment, increment_pct, deload_threshold, deload_pct, created_at, updated_at
FROM progression_rules
WHERE section_exercise_id = ?
`

func (q *Queries) GetProgressionRuleBySectionExerciseID(ctx context.Context, sectionExerciseID int64) (ProgressionRule, error) {
	row := q.db.QueryRowContext(ctx, getProgressionRuleBySectionExerciseID, sectionExerciseID)
	var i ProgressionRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SectionExerciseID,
		&i.Strategy,
		&i.Increment,
		&i.IncrementPct,
		&i.DeloadThreshold,
		&i.DeloadPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgressionRulesBySectionExerciseIDs = `-- name: GetProgressionRulesBySectionExerciseIDs :many
SELECT id, uuid, section_exercise_id, strategy,
       increment, increment_pct, deload_threshold, deload_pct,
       created_at, updated_at
FROM progression_rules
WHERE section_exercise_id IN (/*SLICE:section_exercise_ids*/?)
`

func (q *Queries) GetProgressionRulesBySectionExerciseIDs(ctx context.Context, sectionExerciseIds []int64) ([]ProgressionRule, error) {
	query := getProgressionRulesBySectionExerciseIDs
	var queryParams []interface{}
	if len(sectionExerciseIds) > 0 {
		for _, v := range sectionExerciseIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:section_exercise_ids*/?", strings.Repeat(",?", len(sectionExerciseIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:section_exercise_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressionRule
	for rows.Next() {
		var i ProgressionRule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SectionExerciseID,
			&i.Strategy,
			&i.Increment,
			&i.IncrementPct,
			&i.DeloadThreshold,
			&i.DeloadPct,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionByUUID = `-- name: GetSectionByUUID :one
SELECT id, uuid, program_workout_id, name, sort_order, rest_seconds, created_at, updated_at
FROM sections
WHERE uuid = ?
`

func (q *Queries) GetSectionByUUID(ctx context.Context, uuid string) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSectionByUUID, uuid)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProgramWorkoutID,
		&i.Name,
		&i.SortOrder,
		&i.RestSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionExerciseByUUID = `-- name: GetSectionExerciseByUUID :one
SELECT id, uuid, section_id, exercise_id, target_sets, target_reps, target_weight, target_duration, target_distance, sort_order, notes, created_at, updated_at
FROM section_exercises
WHERE uuid = ?
`

func (q *Queries) GetSectionExerciseByUUID(ctx context.Context, uuid string) (SectionExercise, error) {
	row := q.db.QueryRowContext(ctx, getSectionExerciseByUUID, uuid)
	var i SectionExercise
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SectionID,
		&i.ExerciseID,
		&i.TargetSets,
		&i.TargetReps,
		&i.TargetWeight,
		&i.TargetDuration,
		&i.TargetDistance,
		&i.SortOrder,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionExercisesWithExerciseBySectionIDs = `-- name: GetSectionExercisesWithExerciseBySectionIDs :many
SELECT se.id, se.uuid, se.section_id, se.exercise_id,
       se.target_sets, se.target_reps, se.target_weight,
       se.target_duration, se.target_distance,
       se.sort_order, se.notes, se.created_at, se.updated_at,
       e.uuid AS exercise_uuid, e.name AS exercise_name
FROM section_exercises se
JOIN exercises e ON e.id = se.exercise_id
WHERE se.section_id IN (/*SLICE:section_ids*/?)
ORDER BY se.sort_order
`

type GetSectionExercisesWithExerciseBySectionIDsRow struct {
	ID             int64
	Uuid           string
	SectionID      int64
	ExerciseID     int64
	TargetSets     *int64
	TargetReps     *int64
	TargetWeight   *float64
	TargetDuration *int64
	TargetDistance *float64
	SortOrder      int64
	Notes          *string
	CreatedAt      dbutil.Time
	UpdatedAt      dbutil.Time
	ExerciseUuid   string
	ExerciseName   string
}

func (q *Queries) GetSectionExercisesWithExerciseBySectionIDs(ctx context.Context, sectionIds []int64) ([]GetSectionExercisesWithExerciseBySectionIDsRow, error) {
	query := getSectionExercisesWithExerciseBySectionIDs
	var queryParams []interface{}
	if len(sectionIds) > 0 {
		for _, v := range sectionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:section_ids*/?", strings.Repeat(",?", len(sectionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:section_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSectionExercisesWithExerciseBySectionIDsRow
	for rows.Next() {
		var i GetSectionExercisesWithExerciseBySectionIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SectionID,
			&i.ExerciseID,
			&i.TargetSets,
			&i.TargetReps,
			&i.TargetWeight,
			&i.TargetDuration,
			&i.TargetDistance,
			&i.SortOrder,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExerciseUuid,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionInternalID = `-- name: GetSectionInternalID :one
SELECT id FROM sections
WHERE uuid = ?
`

func (q *Queries) GetSectionInternalID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSectionInternalID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSectionsByWorkoutID = `-- name: GetSectionsByWorkoutID :many

SELECT id, uuid, program_workout_id, name, sort_order, rest_seconds, created_at, updated_at
FROM sections
WHERE program_workout_id = ?
ORDER BY sort_order
`

// ============================================================
// sections
// ============================================================
func (q *Queries) GetSectionsByWorkoutID(ctx context.Context, programWorkoutID int64) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, getSectionsByWorkoutID, programWorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ProgramWorkoutID,
			&i.Name,
			&i.SortOrder,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionsByWorkoutIDs = `-- name: GetSectionsByWorkoutIDs :many
SELECT id, uuid, program_workout_id, name, sort_order, rest_seconds, created_at, updated_at
FROM sections
WHERE program_workout_id IN (/*SLICE:workout_ids*/?)
ORDER BY sort_order
`

func (q *Queries) GetSectionsByWorkoutIDs(ctx context.Context, workoutIds []int64) ([]Section, error) {
	query := getSectionsByWorkoutIDs
	var queryParams []interface{}
	if len(workoutIds) > 0 {
		for _, v := range workoutIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workout_ids*/?", strings.Repeat(",?", len(workoutIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workout_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ProgramWorkoutID,
			&i.Name,
			&i.SortOrder,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutByUUID = `-- name: GetWorkoutByUUID :one
SELECT id, uuid, program_id, name, day_number, sort_order, created_at, updated_at
FROM program_workouts
WHERE uuid = ?
`

func (q *Queries) GetWorkoutByUUID(ctx context.Context, uuid string) (ProgramWorkout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByUUID, uuid)
	var i ProgramWorkout
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProgramID,
		&i.Name,
		&i.DayNumber,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutInternalID = `-- name: GetWorkoutInternalID :one
SELECT id FROM program_workouts
WHERE uuid = ?
`

func (q *Queries) GetWorkoutInternalID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutInternalID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProgressionRule = `-- name: InsertProgressionRule :execresult

INSERT INTO progression_rules (uuid, section_exercise_id, strategy, increment, increment_pct, deload_threshold, deload_pct, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProgressionRuleParams struct {
	Uuid              string
	SectionExerciseID int64
	Strategy          string
	Increment         *float64
	IncrementPct      *float64
	DeloadThreshold   int64
	DeloadPct         float64
	CreatedAt         dbutil.Time
	UpdatedAt         dbutil.Time
}

// ============================================================
// progression_rules
// ============================================================
func (q *Queries) InsertProgressionRule(ctx context.Context, arg InsertProgressionRuleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProgressionRule,
		arg.Uuid,
		arg.SectionExerciseID,
		arg.Strategy,
		arg.Increment,
		arg.IncrementPct,
		arg.DeloadThreshold,
		arg.DeloadPct,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertSection = `-- name: InsertSection :execresult
INSERT INTO sections (uuid, program_workout_id, name, sort_order, rest_seconds, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSectionParams struct {
	Uuid             string
	ProgramWorkoutID int64
	Name             string
	SortOrder        int64
	RestSeconds      *int64
	CreatedAt        dbutil.Time
	UpdatedAt        dbutil.Time
}

func (q *Queries) InsertSection(ctx context.Context, arg InsertSectionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSection,
		arg.Uuid,
		arg.ProgramWorkoutID,
		arg.Name,
		arg.SortOrder,
		arg.RestSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertSectionExercise = `-- name: InsertSectionExercise :execresult
INSERT INTO section_exercises (uuid, section_id, exercise_id, target_sets, target_reps, target_weight, target_duration, target_distance, sort_order, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSectionExerciseParams struct {
	Uuid           string
	SectionID      int64
	ExerciseID     int64
	TargetSets     *int64
	TargetReps     *int64
	TargetWeight   *float64
	TargetDuration *int64
	TargetDistance *float64
	SortOrder      int64
	Notes          *string
	CreatedAt      dbutil.Time
	UpdatedAt      dbutil.Time
}

func (q *Queries) InsertSectionExercise(ctx context.Context, arg InsertSectionExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSectionExercise,
		arg.Uuid,
		arg.SectionID,
		arg.ExerciseID,
		arg.TargetSets,
		arg.TargetReps,
		arg.TargetWeight,
		arg.TargetDuration,
		arg.TargetDistance,
		arg.SortOrder,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertWorkout = `-- name: InsertWorkout :execresult
INSERT INTO program_workouts (uuid, program_id, name, day_number, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertWorkoutParams struct {
	Uuid      string
	ProgramID int64
	Name      string
	DayNumber int64
	SortOrder int64
	CreatedAt dbutil.Time
	UpdatedAt dbutil.Time
}

func (q *Queries) InsertWorkout(ctx context.Context, arg InsertWorkoutParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWorkout,
		arg.Uuid,
		arg.ProgramID,
		arg.Name,
		arg.DayNumber,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const updateProgressionRule = `-- name: UpdateProgressionRule :execresult
UPDATE progression_rules
SET strategy = ?, increment = ?, increment_pct = ?, deload_threshold = ?, deload_pct = ?, updated_at = ?
WHERE section_exercise_id = ?
`

type UpdateProgressionRuleParams struct {
	Strategy          string
	Increment         *float64
	IncrementPct      *float64
	DeloadThreshold   int64
	DeloadPct         float64
	UpdatedAt         dbutil.Time
	SectionExerciseID int64
}

func (q *Queries) UpdateProgressionRule(ctx context.Context, arg UpdateProgressionRuleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProgressionRule,
		arg.Strategy,
		arg.Increment,
		arg.IncrementPct,
		arg.DeloadThreshold,
		arg.DeloadPct,
		arg.UpdatedAt,
		arg.SectionExerciseID,
	)
}

const updateSection = `-- name: UpdateSection :execresult
UPDATE sections
SET name = ?, rest_seconds = ?, updated_at = ?
WHERE uuid = ?
`

type UpdateSectionParams struct {
	Name        string
	RestSeconds *int64
	UpdatedAt   dbutil.Time
	Uuid        string
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSection,
		arg.Name,
		arg.RestSeconds,
		arg.UpdatedAt,
		arg.Uuid,
	)
}

const updateSectionExercise = `-- name: UpdateSectionExercise :execresult
UPDATE section_exercises
SET target_sets = ?, target_reps = ?, target_weight = ?, target_duration = ?, target_distance = ?, notes = ?, updated_at = ?
WHERE uuid = ?
`

type UpdateSectionExerciseParams struct {
	TargetSets     *int64
	TargetReps     *int64
	TargetWeight   *float64
	TargetDuration *int64
	TargetDistance *float64
	Notes          *string
	UpdatedAt      dbutil.Time
	Uuid           string
}

func (q *Queries) UpdateSectionExercise(ctx context.Context, arg UpdateSectionExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSectionExercise,
		arg.TargetSets,
		arg.TargetReps,
		arg.TargetWeight,
		arg.TargetDuration,
		arg.TargetDistance,
		arg.Notes,
		arg.UpdatedAt,
		arg.Uuid,
	)
}

const updateWorkout = `-- name: UpdateWorkout :execresult
UPDATE program_workouts
SET name = ?, day_number = ?, updated_at = ?
WHERE uuid = ?
`

type UpdateWorkoutParams struct {
	Name      string
	DayNumber int64
	UpdatedAt dbutil.Time
	Uuid      string
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkout,
		arg.Name,
		arg.DayNumber,
		arg.UpdatedAt,
		arg.Uuid,
	)
}

const verifySectionBelongsToWorkout = `-- name: VerifySectionBelongsToWorkout :one
SELECT COUNT(*) FROM sections
WHERE id = ? AND program_workout_id = ?
`

type VerifySectionBelongsToWorkoutParams struct {
	ID               int64
	ProgramWorkoutID int64
}

func (q *Queries) VerifySectionBelongsToWorkout(ctx context.Context, arg VerifySectionBelongsToWorkoutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifySectionBelongsToWorkout, arg.ID, arg.ProgramWorkoutID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const verifySectionExerciseBelongsToSection = `-- name: VerifySectionExerciseBelongsToSection :one
SELECT COUNT(*) FROM section_exercises
WHERE id = ? AND section_id = ?
`

type VerifySectionExerciseBelongsToSectionParams struct {
	ID        int64
	SectionID int64
}

func (q *Queries) VerifySectionExerciseBelongsToSection(ctx context.Context, arg VerifySectionExerciseBelongsToSectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifySectionExerciseBelongsToSection, arg.ID, arg.SectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const verifyWorkoutBelongsToProgram = `-- name: VerifyWorkoutBelongsToProgram :one
SELECT COUNT(*) FROM program_workouts
WHERE id = ? AND program_id = ?
`

type VerifyWorkoutBelongsToProgramParams struct {
	ID        int64
	ProgramID int64
}

func (q *Queries) VerifyWorkoutBelongsToProgram(ctx context.Context, arg VerifyWorkoutBelongsToProgramParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifyWorkoutBelongsToProgram, arg.ID, arg.ProgramID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
